extends Node
# Module which defines how to initialize and track an incoming player connection
# request.
#
# The incoming player connection request does not contain any stored
# credentials; the request instead contains a token generated by the
# authentication server.
#
# TODO(minkezhang): Implement authentication server.

@onready var player_state_scene = preload("res://scenes/instances/player/player.tscn")


var _DEBUG_PLAYER_CREDENTIALS = {  # { mint: String -> Dictionary }
	"0xPIZZA": {
		DFStateKeys.KDFPlayerUsername: "Panucci",
	},
	"0xPUB": {
		DFStateKeys.KDFPlayerUsername: "O'ZORGNAX",
	},
}


func verify(sid: int, token: String = "0xPIZZA") -> DFPlayer:
	# TODO(minkezhang): Implement mint matching.
	if token not in _DEBUG_PLAYER_CREDENTIALS:
		return null
	
	var p = player_state_scene.instantiate()
	p.session_id = 0
	p.session_id = sid
	p.name = str(sid)
	p.username = _DEBUG_PLAYER_CREDENTIALS[token][DFStateKeys.KDFPlayerUsername]
	
	return p
