# Module which defines how to initialize and track an incoming player connection
# request.
#
# The incoming player connection request does not contain any stored
# credentials; the request instead contains a token generated by the
# authentication server.
#
# TODO(minkezhang): Implement authentication server.
extends Node

@onready var player_state_scene = preload("res://scenes/instances/player/player.tscn")


var _DEBUG_PLAYER_CREDENTIALS = {  # { mint: String -> Dictionary }
	"0xPIZZA": {
		"name": "Panucci",
	},
	"0xPUB": {
		"name": "O'ZORGNAX",
	},
}


func verify(pid: int, token: String = "0xPIZZA") -> bool:
	# TODO(minkezhang): Implement mint matching.
	if token not in _DEBUG_PLAYER_CREDENTIALS:
		return false
	
	var p = player_state_scene.instantiate()
	p.name = str(pid)
	get_parent().get_node("State/Players").add_child(p, true)
	
	p.session_id = pid
	p.username = _DEBUG_PLAYER_CREDENTIALS[token]["name"]
	
	return true
